### ISSUE TITLE
It appears that dash, s, and face-remap are unused

### ISSUE THREAD

**Issue by abo-abo** [kai2nenobu/guide-key#33]
It's nice to pull in dependencies only if necessary. I don't see any `dash` or `s` functions here.
Also, some or maybe all functions from `face-remap` are autoloaded.

**Comment by kai2nenobu** [comment]
I require `face-remap` to suppress warnings about `text-scale-step` and `text-scale-amount` when compile `guide-key.el`. Indeed I should require `face-remap` only when compile `guide-key.el`. I'll modify it soon.

About `dash` and `s`, I doesn't use them now but use in future version to implement new features and refactor existing codes.  Please do not care about it.
