### ISSUE TITLE
[Proposal] use window-purpose instead of popwin

### ISSUE THREAD

**Issue by bmag** [kai2nenobu/guide-key#40]
Hi, I wrote a package called [window-purpose](https://github.com/bmag/emacs-purpose) that gives a good control over where buffers are displayed. I thought you may be interested use it instead of popwin.
I suggest this because of two issues, one posted on guide-key and one posted on Spacemacs.

[Issue 1](https://github.com/syl20bnr/spacemacs/issues/915): apparently, sometimes when the screen is split, guide-key's window is too small to display all the available keys. Using window-purpose doesn't have this problem.
You can see a visual illustration in a [PR](https://github.com/syl20bnr/spacemacs/pull/1072) that I opened against Spacemacs and will probably get rejected (it was suggested there to make the change in guide-key instead of Spacemacs).

[Issue 2](https://github.com/kai2nenobu/guide-key/issues/36): @paroxyzm asks if guide-key can be displayed in another frame instead of a window. With window-purpose, popping a frame instead of a window is fairly easy.

Tell me if you're interested in this proposal or if you have any questions.

**Comment by boyw165** [comment]
How about using `helm`. Is it possible?

**Comment by bmag** [comment]
I don't understand, what do you mean?

**Comment by stardiviner** [comment]
+1

**Comment by clawoflight** [comment]
Can we reopen this?

**Comment by bmag** [comment]
Why bother? The maintainer hasn't been active in forever. Switch to which-key, it does more than guide-key and is of higher quality.
