### ISSUE TITLE
Guide key bindings with prefix arguments

### ISSUE THREAD

**Issue by kai2nenobu** [kai2nenobu/guide-key#6]

**Comment by whitlockjc** [comment]
I hate to bug you but I've been using guide-key, thanks a lot by the way, and I wanted to enable it for `C-u` but whenever I do, nothing happens.  Is there something special I have to do to get the feature added above?  Here is what I have now:

```elisp
(setq guide-key/guide-key-sequence '("C-x" "C-c" "C-h" "C-u"))

(guide-key-mode 1)

(setq guide-key/recursive-key-sequence-flag t)
(setq guide-key/popup-window-position 'bottom)
```

**Comment by kai2nenobu** [comment]
Maybe, you misunderstand this feature.

This feature doesn't guide key bindings following `C-u` but enables to guide key bindings following both a normal prefix and a prefix with argument (like `C-x` and `C-u C-x`). 
So it is meaningless to add `C-u` to `guide-key/guide-key-sequence`.

Best regards.

**Comment by whitlockjc** [comment]
Ah, that was it.  I did misunderstand.  Thanks for clarifying.
